/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_qiujuer_genius_blur_StackNative */

#ifndef _Included_net_qiujuer_genius_blur_StackNative
#define _Included_net_qiujuer_genius_blur_StackNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_qiujuer_genius_blur_StackNative
 * Method:    blurPixels
 * Signature: ([IIII)V
 */
JNIEXPORT void JNICALL Java_net_qiujuer_genius_blur_StackNative_blurPixels
  (JNIEnv *, jclass, jintArray, jint, jint, jint);

/*
 * Class:     net_qiujuer_genius_blur_StackNative
 * Method:    blurBitmap
 * Signature: (Landroid/graphics/Bitmap;I)V
 */
JNIEXPORT void JNICALL Java_net_qiujuer_genius_blur_StackNative_blurBitmap
  (JNIEnv *, jclass, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
