/*
 * Copyright (C) 2014 Qiujuer <qiujuer@live.cn>
 * WebSite http://www.qiujuer.net
 * Created 12/25/2014
 * Changed 03/08/2015
 * Version 3.0.0
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_qiujuer_genius_ui_app_BlurNative */

#ifndef _Included_net_qiujuer_genius_ui_app_BlurNative
#define _Included_net_qiujuer_genius_ui_app_BlurNative
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     net_qiujuer_genius_ui_app_BlurNative
	 * Method:    blurPixels
	 * Signature: ([IIII)V
	 */
	JNIEXPORT void JNICALL Java_net_qiujuer_genius_ui_app_BlurNative_blurPixels
		(JNIEnv *, jclass, jintArray, jint, jint, jint);

	/*
	 * Class:     net_qiujuer_genius_ui_app_BlurNative
	 * Method:    blurBitmap
	 * Signature: (Landroid/graphics/Bitmap;I)V
	 */
	JNIEXPORT void JNICALL Java_net_qiujuer_genius_ui_app_BlurNative_blurBitmap
		(JNIEnv *, jclass, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
