/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_qiujuer_genius_graphics_Blur */

#ifndef _Included_net_qiujuer_genius_graphics_Blur
#define _Included_net_qiujuer_genius_graphics_Blur
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Java_net_qiujuer_genius_graphics_Blur
 * Method:    nativeStackBlurPixels
 * Signature: ([IIII)V
 */
JNIEXPORT void JNICALL
        Java_net_qiujuer_genius_graphics_Blur_nativeStackBlurPixels
        (JNIEnv *, jclass, jintArray, jint, jint, jint);

/*
 * Class:     Java_net_qiujuer_genius_graphics_Blur
 * Method:    nativeStackBlurBitmap
 * Signature: (Landroid/graphics/Bitmap;I)V
 */
JNIEXPORT void JNICALL
        Java_net_qiujuer_genius_graphics_Blur_nativeStackBlurBitmap
        (JNIEnv *, jclass, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif