/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package net.qiujuer.genius;

public final class R {
    public static final class array {
        public static int blood = 0x7f020000;
        public static int blossom = 0x7f020001;
        public static int candy = 0x7f020002;
        public static int dark = 0x7f020003;
        public static int deep = 0x7f020004;
        public static int grape = 0x7f020005;
        public static int grass = 0x7f020006;
        public static int orange = 0x7f020007;
        public static int sand = 0x7f020008;
        public static int sea = 0x7f020009;
        public static int sky = 0x7f02000a;
        public static int snow = 0x7f02000b;
    }

    public static final class attr {
        /**
         * <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
         * Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
         * in (inches), mm (millimeters).
         * <p>This may also be a reference to a resource (in the form
         * "<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
         * theme attribute (in the form
         * "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
         * containing a value of this type.
         */
        public static int gm_blockButtonEffectHeight = 0x7f010008;
        /**
         * <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
         * Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
         * in (inches), mm (millimeters).
         * <p>This may also be a reference to a resource (in the form
         * "<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
         * theme attribute (in the form
         * "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
         * containing a value of this type.
         */
        public static int gm_cornerRadius = 0x7f010000;
        /**
         * <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
         * <p>This may also be a reference to a resource (in the form
         * "<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
         * theme attribute (in the form
         * "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
         * containing a value of this type.
         */
        public static int gm_fontExtension = 0x7f010001;
        /**
         * <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
         * <p>This may also be a reference to a resource (in the form
         * "<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
         * theme attribute (in the form
         * "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
         * containing a value of this type.
         */
        public static int gm_fontFamily = 0x7f010002;
        /**
         * <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
         * <p>This may also be a reference to a resource (in the form
         * "<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
         * theme attribute (in the form
         * "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
         * containing a value of this type.
         */
        public static int gm_fontWeight = 0x7f010003;
        /**
         * <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
         * <p>This may also be a reference to a resource (in the form
         * "<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
         * theme attribute (in the form
         * "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
         * containing a value of this type.
         */
        public static int gm_isAutoMove = 0x7f010004;
        /**
         * <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
         * <p>This may also be a reference to a resource (in the form
         * "<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
         * theme attribute (in the form
         * "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
         * containing a value of this type.
         */
        public static int gm_isMaterial = 0x7f010005;
        /**
         * <p>May be an integer value, such as "<code>100</code>".
         * <p>This may also be a reference to a resource (in the form
         * "<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
         * theme attribute (in the form
         * "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
         * containing a value of this type.
         * <p>May be one of the following constant values.</p>
         * <table>
         * <colgroup align="left" />
         * <colgroup align="left" />
         * <colgroup align="left" />
         * <tr><th>Constant</th><th>Value</th><th>Description</th></tr>
         * <tr><td><code>none</code></td><td>0</td><td></td></tr>
         * <tr><td><code>dark</code></td><td>1</td><td></td></tr>
         * <tr><td><code>light</code></td><td>2</td><td></td></tr>
         * </table>
         */
        public static int gm_textAppearance = 0x7f010006;
        /**
         * <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
         * or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static int gm_theme = 0x7f010007;
    }

    public static final class color {
        public static int blood_dark = 0x7f030000;
        public static int blood_darker = 0x7f030001;
        public static int blood_light = 0x7f030002;
        public static int blood_primary = 0x7f030003;
        public static int blossom_dark = 0x7f030004;
        public static int blossom_darker = 0x7f030005;
        public static int blossom_light = 0x7f030006;
        public static int blossom_primary = 0x7f030007;
        public static int candy_dark = 0x7f030008;
        public static int candy_darker = 0x7f030009;
        public static int candy_light = 0x7f03000a;
        public static int candy_primary = 0x7f03000b;
        public static int dark_dark = 0x7f03000c;
        public static int dark_darker = 0x7f03000d;
        public static int dark_light = 0x7f03000e;
        public static int dark_primary = 0x7f03000f;
        public static int deep_dark = 0x7f030010;
        public static int deep_darker = 0x7f030011;
        public static int deep_light = 0x7f030012;
        public static int deep_primary = 0x7f030013;
        public static int grape_dark = 0x7f030014;
        public static int grape_darker = 0x7f030015;
        public static int grape_light = 0x7f030016;
        public static int grape_primary = 0x7f030017;
        public static int grass_dark = 0x7f030018;
        public static int grass_darker = 0x7f030019;
        public static int grass_light = 0x7f03001a;
        public static int grass_primary = 0x7f03001b;
        public static int orange_dark = 0x7f03001c;
        public static int orange_darker = 0x7f03001d;
        public static int orange_light = 0x7f03001e;
        public static int orange_primary = 0x7f03001f;
        public static int sand_dark = 0x7f030020;
        public static int sand_darker = 0x7f030021;
        public static int sand_light = 0x7f030022;
        public static int sand_primary = 0x7f030023;
        public static int sea_dark = 0x7f030024;
        public static int sea_darker = 0x7f030025;
        public static int sea_light = 0x7f030026;
        public static int sea_primary = 0x7f030027;
        public static int sky_dark = 0x7f030028;
        public static int sky_darker = 0x7f030029;
        public static int sky_light = 0x7f03002a;
        public static int sky_primary = 0x7f03002b;
        public static int snow_dark = 0x7f03002c;
        public static int snow_darker = 0x7f03002d;
        public static int snow_light = 0x7f03002e;
        public static int snow_primary = 0x7f03002f;
    }

    public static final class id {
        public static int dark = 0x7f040000;
        public static int light = 0x7f040001;
        public static int none = 0x7f040002;
    }

    public static final class styleable {
        /**
         * Attributes that can be used with a MaterialButton.
         * <p>Includes the following attributes:</p>
         * <table>
         * <colgroup align="left" />
         * <colgroup align="left" />
         * <tr><th>Attribute</th><th>Description</th></tr>
         * <tr><td><code>{@link #MaterialButton_gm_blockButtonEffectHeight net.qiujuer.genius:gm_blockButtonEffectHeight}</code></td><td></td></tr>
         * <tr><td><code>{@link #MaterialButton_gm_cornerRadius net.qiujuer.genius:gm_cornerRadius}</code></td><td></td></tr>
         * <tr><td><code>{@link #MaterialButton_gm_fontExtension net.qiujuer.genius:gm_fontExtension}</code></td><td></td></tr>
         * <tr><td><code>{@link #MaterialButton_gm_fontFamily net.qiujuer.genius:gm_fontFamily}</code></td><td></td></tr>
         * <tr><td><code>{@link #MaterialButton_gm_fontWeight net.qiujuer.genius:gm_fontWeight}</code></td><td></td></tr>
         * <tr><td><code>{@link #MaterialButton_gm_isAutoMove net.qiujuer.genius:gm_isAutoMove}</code></td><td></td></tr>
         * <tr><td><code>{@link #MaterialButton_gm_isMaterial net.qiujuer.genius:gm_isMaterial}</code></td><td></td></tr>
         * <tr><td><code>{@link #MaterialButton_gm_textAppearance net.qiujuer.genius:gm_textAppearance}</code></td><td></td></tr>
         * <tr><td><code>{@link #MaterialButton_gm_theme net.qiujuer.genius:gm_theme}</code></td><td></td></tr>
         * </table>
         *
         * @see #MaterialButton_gm_blockButtonEffectHeight
         * @see #MaterialButton_gm_cornerRadius
         * @see #MaterialButton_gm_fontExtension
         * @see #MaterialButton_gm_fontFamily
         * @see #MaterialButton_gm_fontWeight
         * @see #MaterialButton_gm_isAutoMove
         * @see #MaterialButton_gm_isMaterial
         * @see #MaterialButton_gm_textAppearance
         * @see #MaterialButton_gm_theme
         */
        public static final int[] MaterialButton = {
                0x7f010000, 0x7f010001, 0x7f010002, 0x7f010003,
                0x7f010004, 0x7f010005, 0x7f010006, 0x7f010007,
                0x7f010008
        };
        /**
         * <p>This symbol is the offset where the {@link net.qiujuer.genius.R.attr#gm_blockButtonEffectHeight}
         * attribute's value can be found in the {@link #MaterialButton} array.
         * <p/>
         * <p/>
         * <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
         * Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
         * in (inches), mm (millimeters).
         * <p>This may also be a reference to a resource (in the form
         * "<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
         * theme attribute (in the form
         * "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
         * containing a value of this type.
         *
         * @attr name net.qiujuer.genius:gm_blockButtonEffectHeight
         */
        public static int MaterialButton_gm_blockButtonEffectHeight = 8;
        /**
         * <p>This symbol is the offset where the {@link net.qiujuer.genius.R.attr#gm_cornerRadius}
         * attribute's value can be found in the {@link #MaterialButton} array.
         * <p/>
         * <p/>
         * <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
         * Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
         * in (inches), mm (millimeters).
         * <p>This may also be a reference to a resource (in the form
         * "<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
         * theme attribute (in the form
         * "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
         * containing a value of this type.
         *
         * @attr name net.qiujuer.genius:gm_cornerRadius
         */
        public static int MaterialButton_gm_cornerRadius = 0;
        /**
         * <p>This symbol is the offset where the {@link net.qiujuer.genius.R.attr#gm_fontExtension}
         * attribute's value can be found in the {@link #MaterialButton} array.
         * <p/>
         * <p/>
         * <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
         * <p>This may also be a reference to a resource (in the form
         * "<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
         * theme attribute (in the form
         * "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
         * containing a value of this type.
         *
         * @attr name net.qiujuer.genius:gm_fontExtension
         */
        public static int MaterialButton_gm_fontExtension = 1;
        /**
         * <p>This symbol is the offset where the {@link net.qiujuer.genius.R.attr#gm_fontFamily}
         * attribute's value can be found in the {@link #MaterialButton} array.
         * <p/>
         * <p/>
         * <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
         * <p>This may also be a reference to a resource (in the form
         * "<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
         * theme attribute (in the form
         * "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
         * containing a value of this type.
         *
         * @attr name net.qiujuer.genius:gm_fontFamily
         */
        public static int MaterialButton_gm_fontFamily = 2;
        /**
         * <p>This symbol is the offset where the {@link net.qiujuer.genius.R.attr#gm_fontWeight}
         * attribute's value can be found in the {@link #MaterialButton} array.
         * <p/>
         * <p/>
         * <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
         * <p>This may also be a reference to a resource (in the form
         * "<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
         * theme attribute (in the form
         * "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
         * containing a value of this type.
         *
         * @attr name net.qiujuer.genius:gm_fontWeight
         */
        public static int MaterialButton_gm_fontWeight = 3;
        /**
         * <p>This symbol is the offset where the {@link net.qiujuer.genius.R.attr#gm_isAutoMove}
         * attribute's value can be found in the {@link #MaterialButton} array.
         * <p/>
         * <p/>
         * <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
         * <p>This may also be a reference to a resource (in the form
         * "<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
         * theme attribute (in the form
         * "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
         * containing a value of this type.
         *
         * @attr name net.qiujuer.genius:gm_isAutoMove
         */
        public static int MaterialButton_gm_isAutoMove = 4;
        /**
         * <p>This symbol is the offset where the {@link net.qiujuer.genius.R.attr#gm_isMaterial}
         * attribute's value can be found in the {@link #MaterialButton} array.
         * <p/>
         * <p/>
         * <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
         * <p>This may also be a reference to a resource (in the form
         * "<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
         * theme attribute (in the form
         * "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
         * containing a value of this type.
         *
         * @attr name net.qiujuer.genius:gm_isMaterial
         */
        public static int MaterialButton_gm_isMaterial = 5;
        /**
         * <p>This symbol is the offset where the {@link net.qiujuer.genius.R.attr#gm_textAppearance}
         * attribute's value can be found in the {@link #MaterialButton} array.
         * <p/>
         * <p/>
         * <p>May be an integer value, such as "<code>100</code>".
         * <p>This may also be a reference to a resource (in the form
         * "<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
         * theme attribute (in the form
         * "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
         * containing a value of this type.
         * <p>May be one of the following constant values.</p>
         * <table>
         * <colgroup align="left" />
         * <colgroup align="left" />
         * <colgroup align="left" />
         * <tr><th>Constant</th><th>Value</th><th>Description</th></tr>
         * <tr><td><code>none</code></td><td>0</td><td></td></tr>
         * <tr><td><code>dark</code></td><td>1</td><td></td></tr>
         * <tr><td><code>light</code></td><td>2</td><td></td></tr>
         * </table>
         *
         * @attr name net.qiujuer.genius:gm_textAppearance
         */
        public static int MaterialButton_gm_textAppearance = 6;
        /**
         * <p>This symbol is the offset where the {@link net.qiujuer.genius.R.attr#gm_theme}
         * attribute's value can be found in the {@link #MaterialButton} array.
         * <p/>
         * <p/>
         * <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
         * or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         *
         * @attr name net.qiujuer.genius:gm_theme
         */
        public static int MaterialButton_gm_theme = 7;
    }

    ;
}